config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :stats, only: :index
  end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/stats.rb
class Stats < WordsCounted::Counter

  # inherited instance methods
  # token_count
  # uniq_token_count
  # char_count
  # token_frequency
  # token_lengths
  # token_density
  # most_frequent_tokens
  # longest_tokens
  # average_chars_per_token

  DELIMITERS = ['-', '—', '―', '~', '\\', '/', '|', '+', '\'', '‘', '’', ' ']
  SEPARATOR = '-'
  TOKEN_REGEXP = /[\p{Alpha}\-']+/

  attr_accessor :slug
  attr_reader   :tokens

  def initialize(slug)
    @slug = slug
    super
  end

  def top(num = 25)
    num = self.tokens.size >= 25 ? num : self.tokens.size
    token_frequency.first(num).to_h
  end

  def summary
    {
      token_count: self.token_count,
      uniq_token_count: self.uniq_token_count,
      characters_count: self.char_count,
      average_chars_per_token: self.average_chars_per_token
    }
  end

  def self.tokenize(slug, separator: SEPARATOR, **options )
    token = slug.downcase.strip.gsub(separator, ' ') if DELIMITERS.include? separator
    tokenized = WordsCounted::Tokeniser.send(:new, token).tokenise(**options)
    send(:new, tokenized)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :slug, :body)
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stats

  def index
  end

  private

  def stats_params
    params.permit(:post_id)
  end

  def set_stats
    @post = Post.friendly.find(stats_params[:post_id])
    @stats = Stats.tokenize(stats_params[:post_id], exclude: ["some", "words"])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def object_errors_for(object, attribute)
    return nil unless object.errors.any?
    content_tag(:div, nil, class: %w[d-block invalid-feedback], id: "#{dom_id_for(object, attribute)}_feedback") do
      object.errors.full_messages_for(attribute).to_sentence
    end
  end

  def dom_id_for(object, prefix)
      model_name = object.model_name.param_key unless object.is_a? Class
      prefix ? "#{model_name}_#{prefix}" : object
  end

  def bootstrap_class_for(flash_type)
    classes = {
      success:  'alert alert-success alert-dismissible fade show',
      error:    'alert alert-danger alert-dismissible fade show',
      alert:    'alert alert-warning alert-dismissible fade show',
      notice:   'alert alert-info alert-dismissible fade show'
    }
    classes[flash_type.to_sym] || classes[:notice]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/application/_flash.html.erb
<% flash.each  do |flash_type, message| %>
	<%= content_tag :div, nil, class: bootstrap_class_for(flash_type), role: 'alert' do  %>
		<%= content_tag :div, class: 'container' do %>
			<%= button_tag "", { class: "btn-close",  data: {bs_dismiss: 'alert'}, "aria-label": "Close", type: 'button', name: nil } %>
			<%= content_tag :p, class: 'mb-0' do %>
				<%= message %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>UrlWordCounter</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
		<%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
	</head>
	<body class="container-fluid">
		<div class="container flash">
			<%= render 'flash' %>
		</div>
		<%= yield %>
	</body>
</html>

app/views/posts/_form.html.erb
<div class="container mt-4">
	<div>
		<h3>Post</h3>
	</div>
	<%= form_with(model: post) do |form| %>
		<div class="form-group mb-2">
			<%= form.label :title, class: "form-label" %>
			<%= form.text_field :title, class: "form-control" %>
			<% object_errors_for post, :title %>
		</div>
		<% if form.object.persisted? %>
			<div class="form-group mb-2">
				<%= form.label :slug, class: 'form-label' %>
				<%= form.text_field :slug, class: 'form-control' %>
				<% object_errors_for post, :title %>
			</div>
		<% end %>
		<div class="form-group mb-2">
			<%= form.label :body, class: 'form-label' %>
			<%= form.text_area :body, rows: 8, class: 'form-control' %>
			<% object_errors_for post, :title %>
		</div>
		<div class="form-group d-inline-block">
			<%= form.submit "Submit", class: "btn btn-light border-0" %>
		</div>
		<div class="form-group d-inline-block">
			<%= link_to "Back", posts_path, class: "btn btn-light border-0" %>
		</div>
	<% end %>
</div>

app/views/posts/_links.html.erb
<div class="my-3">
	<%= link_to "Edit", edit_post_path(@post), class: "btn btn-light border-0" %>
	<%= button_to "Destroy", @post,
            method: :delete, form: { class: "button_to btn btn-light border-0 ms-1" } %>
	<%= link_to "Back", posts_path, class: "btn btn-light border-0 ms-1" %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
	<div class="mb2">
		<p>
			<strong>Title</strong>
			<%= post.title %>
		</p>
	</div>
	<p>
		<strong>Slug</strong>
		<%= post.slug %>
	</p>
	<div>
		<%= post.body %>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="container w-50 my-4">
	<div>
		<h1>Editing post</h1>
	</div>
	<%= render "form", post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container mt-5">
	<h1>Posts</h1>
	<div id="posts">
		<% @posts.each do |post| %>
			<div class="row title border border-1 rounded-2 mb-2">
				<div class="col-10 my-auto">
					<div class="py-1">
						<p class="mb-0 align-middle"><%= post.title.strip.truncate(80) %></p>
					</div>
				</div>
				<div class="col-1 my-auto">
					<div class="py-1 mx-2">
						<%= link_to "Show", post, class: 'link-to btn btn-light' %>
					</div>
				</div>
				<div class="col-1 my-auto">
					<div class="py-1 statis">
						<a class="btn btn-light"
                                data-bs-toggle="collapse"
                                href="#collapseStats_<%= dom_id(post) %>"
                                role="button"
                                aria-expanded="false"
                                aria-controls="collapseStats_<%= dom_id(post) %>">
							Stats
						</a>
					</div>
				</div>
				<div class="collapse my-2 px-2" id="collapseStats_<%= dom_id(post) %>" >
					<%= turbo_frame_tag post_stats_path(post.id).parameterize, src: post_stats_path(post), loading: 'lazy' %>
				</div>
			</div>
		<% end %>
	</div>
	<%= link_to "New post", new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container w-50">
	<%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<div class="container w-50 my-4">
	<%= render @post %>
	<div class="my-3">
		<%= link_to "Edit", edit_post_path(@post), class: "btn btn-light border-0" %>
		<%= button_to "Destroy", @post,
            method: :delete, form: { class: "button_to btn btn-light border-0 ms-1" } %>
		<%= link_to "Back", posts_path, class: "btn btn-light border-0 ms-1" %>
	</div>
</div>

app/views/stats/_stats.html.erb
<% title_size = capture do %>
	<%= stats.tokens.size >= 25 ? 25 : stats.tokens.size %>
<% end %>
<%= turbo_frame_tag post_stats_path(post.id).parameterize do %>
	<div class="row">
		<div class="col-12 mx-0">
			<div class="border border-1 rounded-2">
				<div class="m-2">
					<h5>Top <%= title_size%> Words</h5>
				</div>
				<hr class="mx-2">
				<div class="d-flex flex-wrap">
					<% stats.top(title_size.to_i).each do |word, count| %>
						<div class="border border-1 rounded-2 m-2 px-4 py-2 position-relative words">
							<p class="mb-0">
								<%= word.upcase %>
								<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-dark bg-opacity-50">
									<%= count %>
								</span>
							</p>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/stats/index.html.erb
<%= render 'stats', stats: @stats, post: @post %>